version: '3'
services:

  #PHP Service
  cdn:
    build:
      context: ./php
      dockerfile: Dockerfile
    # image: digitalocean.com/php
    container_name: cdn
    healthcheck:
      test: php-fpm -t
    depends_on:
      - redis
      - db
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: cdn
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./cdn_client/:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
      - ./php/fpm/www.conf:/usr/local/etc/php-fpm.d/www.conf
    command:
      - /bin/bash 
      - -c 
      - | 
        composer install
        composer remove laravel/sanctum
        composer require barryvdh/laravel-debugbar --dev
        php-fpm
    # tail -f /dev/null
    networks:
      - app-network

  #Nginx
  nginx:
    image: nginx:latest
    container_name: nginx
    depends_on:
      cdn:
        condition: service_healthy
    restart: unless-stopped
    tty: true
    ports:
      - "8023:80"
    volumes:
      - ./cdn_client/:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - ./nginx/log/:/var/log/nginx/
    networks:
      - app-network

  #MySQL Service
  db:
    image: mariadb:10.6
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "3310:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "!QAZ2wsx"
      MARIADB_USER: Gary
      MARIADB_PASSWORD: Ab123456
      MYSQL_DATABASE: cdn
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql/
      - ./db/config/mysql_conf:/etc/mysql/conf.d
      - ./db/config/mysql_init:/docker-entrypoint-initdb.d
    networks:
      - app-network

  #Redis
  redis:
    image: redis:7.0
    container_name: redis
    restart: always
    ports:
      - 6377:6379
    expose:
      - "6379"
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis.conf
    command: redis-server /usr/local/etc/redis.conf
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge
#Volumes
volumes:
  dbdata:
    driver: local
