version: '3'
services:

  #PHP Service
  cdn:
    build:
      context: ./php/fpm
      dockerfile: Dockerfile
    # image: digitalocean.com/php
    container_name: cdn
    healthcheck:
      test: php-fpm -t
    depends_on:
      - redis
      - db
    # restart: unless-stopped
    tty: true
    environment:
      TZ: "Asia/Taipei"
      SERVICE_NAME: cdn
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./cdn_client/:/var/www
      - ./laravel_env_volume/.env:/var/www/.env
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
      - ./php/fpm/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./php/fpm/log:/var/www/storage/logs
    command:
      - /bin/bash
      - -c
      - |
        composer install
        php artisan migrate
        php-fpm
      # composer remove laravel/sanctum
      # composer dumpautoload
      # composer require barryvdh/laravel-debugbar --dev
      # tail -f /dev/null
    networks:
      - cdn-client

  #Nginx
  nginx:
    image: nginx:latest
    container_name: nginx
    depends_on:
      cdn:
        condition: service_healthy
    restart: unless-stopped
    tty: true
    ports:
      - "8023:80"
    environment:
      TZ: "Asia/Taipei"
    volumes:
      - ./cdn_client/:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - ./nginx/log/:/var/log/nginx/
    networks:
      - cdn-client

  #MySQL Service
  db:
    image: mariadb:10.6
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "3310:3306"
    environment:
      TZ: "Asia/Taipei"
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql/
      - ./db/config/mysql_conf:/etc/mysql/conf.d
      - ./db/config/mysql_init:/docker-entrypoint-initdb.d
    networks:
      - cdn-client

  #Redis
  redis:
    image: redis:7.0
    container_name: redis
    restart: always
    ports:
      - 6377:6379
    expose:
      - "6379"
    environment:
      TZ: "Asia/Taipei"
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis.conf
    command: redis-server /usr/local/etc/redis.conf
    networks:
      - cdn-client

#Docker Networks
networks:
  cdn-client:
    driver: bridge
#Volumes
volumes:
  dbdata:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './db/db_dump'
