version: '3.8'
services:

  #PHP Service
  cdn_client_cdn:
    user: "1000:1000"
    build:
      context: ./php/fpm
      dockerfile: Dockerfile
    # image: digitalocean.com/php
    container_name: cdn_client_cdn
    healthcheck:
      test: php-fpm -t
    depends_on:
      - cdn_client_redis
      - cdn_client_db
    # restart: unless-stopped
    tty: true
    environment:
      TZ: "Asia/Taipei"
      SERVICE_NAME: cdn_client_cdn
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./cdn_client/:/var/www
      - ./laravel_env_volume/.env:/var/www/.env
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
      - ./php/fpm/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./php/fpm/log:/var/www/storage/logs
    command:
      - /bin/bash
      - -c
      - |
        composer install
        php artisan migrate
        php artisan l5-swagger:generate
        php-fpm
      # composer require barryvdh/laravel-debugbar --dev
      # tail -f /dev/null
    networks:
      - cdn-client-network

  #Nginx
  cdn_client_nginx:
    image: nginx:latest
    container_name: cdn_client_nginx
    depends_on:
      cdn_client_cdn:
        condition: service_healthy
    restart: unless-stopped
    tty: true
    ports:
      - "8024:80"
    environment:
      TZ: "Asia/Taipei"
    volumes:
      - ./cdn_client/:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - ./nginx/log/:/var/log/nginx/
    networks:
      - cdn-client-network

  #MySQL Service
  cdn_client_db:
    image: mariadb:10.6
    container_name: cdn_client_db
    restart: unless-stopped
    tty: true
    ports:
      - "3311:3306"
    environment:
      TZ: "Asia/Taipei"
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./db/db_dump:/var/lib/mysql/
      - ./db/config/mysql_conf:/etc/mysql/conf.d
      - ./db/config/mysql_init:/docker-entrypoint-initdb.d
    networks:
      - cdn-client-network

  #Redis
  cdn_client_redis:
    image: redis:7.0
    container_name: cdn_client_redis
    restart: always
    ports:
      - 6378:6379
    expose:
      - "6379"
    environment:
      TZ: "Asia/Taipei"
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis.conf
    command: redis-server /usr/local/etc/redis.conf
    networks:
      - cdn-client-network

#Docker Networks
networks:
  cdn-client-network:
    driver: bridge
